- hosts: jenkins
  become: true
  become_user: root
  tasks:
    - name: Install java openjdk-21-jdk
      ansible.builtin.apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes

    - name: Aditionally jenkins key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Aditionally jenkins repo
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start jenkins
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    - name: Jenkins password
      ansible.builtin.command:
        cmd: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Prints two lines of messages, but only if there is an environment value set
      ansible.builtin.debug:
        msg: "The password is {{ jenkins_password.stdout }}"
